#! /usr/bin/env python3
import socket
import sys
from scan_tools import nmap_calls

host = sys.argv[1]

host = socket.gethostbyname(host)

print('Running probe...')
result = nmap_calls.host_up(host)
if result == 0:
    exit()

print('\nScanning host for ports...')
ports = nmap_calls.port_scan_top(host)
if ports == 0:
    print('No ports open')
    exit()

print('\nFinding port versions...')
nmap_calls.service_version(host, ports)

service_ports = ['21','443']

if "21" in ports or "443" in ports:
    print('\nSeareching for info...')
    for port in ports:
        match port:
            case port_num if port_num in service_ports:
                nmap_calls.info_search(host, port)
            
print('\nScan completed')

